name: Publish Package to npm

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  # Only run publish jobs if both conditions are met:
  # 1. Push is to main branch
  # 2. Has a version tag
  should-publish:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - run: echo "Checking publish conditions"

  build:
    needs: should-publish
    if: needs.should-publish.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build
        run: bun run build:all

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          registry-url: "https://registry.npmjs.org"

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build:all

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
